### ISSUE TITLE
Sum Random Crash. Its right after mod loading/while

### ISSUE THREAD

**Issue by 1ue999** [MEEPofFaith/hallucinogen#2]
Mindustry has crashed. How unfortunate.
Version: steam build 146
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 4074mb
Cores: 8
Mods: hallucinogen:7

java.lang.RuntimeException: Error loading mod hallucinogen
	at mindustry.mod.Mods.contextRun(Mods.java:797)
	at mindustry.mod.Mods.lambda$eachClass$30(Mods.java:785)
	at arc.struct.Seq.each(Seq.java:182)
	at mindustry.mod.Mods.eachClass(Mods.java:785)
	at mindustry.ClientLauncher.update(ClientLauncher.java:222)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: arc.util.ArcRuntimeException: File not found: shaders\passThrough.frag (internal)
	at arc.files.Fi.read(Fi.java:199)
	at arc.files.Fi.length(Fi.java:892)
	at arc.files.Fi.estimateLength(Fi.java:317)
	at arc.files.Fi.readString(Fi.java:275)
	at arc.files.Fi.readString(Fi.java:266)
	at arc.graphics.gl.Shader.<init>(Shader.java:124)
	at drunkustry.graphics.DrunkShaders$PassthroughShader.<init>(DrunkShaders.java:175)
	at drunkustry.graphics.DrunkShaders.init(DrunkShaders.java:23)
	at drunkustry.Drunkdustry.init(Drunkdustry.java:16)
	at mindustry.mod.Mods.lambda$eachClass$29(Mods.java:785)
	at mindustry.mod.Mods.contextRun(Mods.java:795)
	... 8 more

**Comment by MEEPofFaith** [comment]
How it's even possible to fail to find one of my shader files????

**Comment by 1ue999** [comment]
i have no idea. all i know it (the newest version) dosnt work with the steam version (maybe also other versions, didnt test)

**Comment by coaldeficit** [comment]
@MEEPofFaith the version of the mod obtained through downloading via mod browser has the shader filename as "passthrough.frag" while it checks for "passThrough.frag". it looks like you've already fixed this in the source code so i imagine this could be fixed by just making a new release

**Comment by MEEPofFaith** [comment]
Why did I never release that
